---
# tasks file for configure-worker
- name: Copy the join command to server location
  copy:
    src: join-command
    dest: /tmp/join-command.sh
    force: yes
    mode: 0777

- name: Check previous createad kubelet
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: stat_result
  ignore_errors: True

- name: Check kubeket service status
  command: systemctl status kubelet
  when: stat_result.stat.exists
  ignore_errors: True
  register: kubelet_status

- name: Reset kubelet if previous instalation is found
  command: kubeadm reset -f
  when: (stat_result.stat.exists) and (kubelet_status.rc > 0)

- name: Join the node to cluster
  command: sh /tmp/join-command.sh
  when: not (stat_result.stat.exists) or (kubelet_status.rc > 0)

- name: Remove join-command on remote node
  file:
    path: /tmp/join-command.sh
    state: absent
