- name: Install docker and its dependecies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - docker-scan-plugin
      - docker-ce-rootless-extras
      - containerd.io
