- name: Check if kubernetes cluster is running fine
  shell: kubectl get nodes || false
  register: get_node_command
  failed_when: false

- name: Pull k8s control-plane images
  command: kubeadm config images pull
  when: not get_node_command.rc == 0

- name: Check previous createad kubelet
  stat:
    path: /etc/kubernetes/manifests/etcd.yaml
  register: stat_result
  ignore_errors: True

- name: Reset Kubernetes cluster if previous instalation is found
  command: kubeadm reset -f
  when: (stat_result.stat.exists) and (get_node_command.rc > 0)

- name: Initialize the Kubernetes cluster using kubeadm
  shell: kubeadm init --apiserver-advertise-address="{{ansible_eth1.ipv4.address}}" --apiserver-cert-extra-sans="{{ansible_eth1.ipv4.address}}" --pod-network-cidr=192.168.0.0/16
  when: not get_node_command.rc == 0
