- name: Configure network modules
  blockinfile:
    path: /etc/modules-load.d/k8s.conf
    create: yes
    block: |
      br_netfilter
      overlay

- name: Configure kernel parameters
  blockinfile:
    path: /etc/sysctl.d/k8s.conf
    create: yes
    block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
  # notify:
  #   - reload_sysctl
  register: sysctl_restart_required

# workaround because handlers exection failure while using vagrant
- name: reload_sysctl
  shell: sysctl --system
  when: sysctl_restart_required.changed
